runtime: nodejs20

handlers:
  - url: /static
    static_dir: static
    http_headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET"
      Access-Control-Allow-Headers: "Content-Type"
    secure: always

  - url: /.*
    script: auto

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  NODE_ENV: 'production'



